version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./routes:/backend/routes
      - ./views:/backend/views
      - ./app.js:/backend/app.js
